/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Amplify, { Auth } from 'aws-amplify';

Amplify.configure({
    Auth: {

        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: 'us-east-2:78e8d674-843e-425d-825d-ab5bc50f9d61',

        // REQUIRED - Amazon Cognito Region
        region: 'us-east-2',

        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'us-east-2_74G5gYkI4',

        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: '2m2tcu8bvote9guum4rvc9tha2'
        }
    }
);

// You can get the current config object
const currentConfig = Auth.configure();

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:78e8d674-843e-425d-825d-ab5bc50f9d61",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_74G5gYkI4",
    "aws_user_pools_web_client_id": "2m2tcu8bvote9guum4rvc9tha2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f66gikdcn5gwvcprjdnqhmxvdu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://8vn0tgmi2b.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
