/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:78e8d674-843e-425d-825d-ab5bc50f9d61",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_74G5gYkI4",
    "aws_user_pools_web_client_id": "2m2tcu8bvote9guum4rvc9tha2",
    "oauth": {}
};


export default awsmobile;
